### ISSUE TITLE
Is still a single relationship extraction on the CDR dataset?

### ISSUE THREAD

**Issue by yuanxiaosc** [patverga/bran#12]
Although entities may appear in many sentences, there is still only one pair of relationships in each paragraph that needs to be judged?

**Comment by patverga** [comment]
Yes, all the predictions are at the entity level rather than the mention level. As you note, an entity can appear in many sentences, each of these is referred to as a single mention. When we are making predictions about the entities, we are really asking if one or more of the mentions express the relation.

**Comment by yuanxiaosc** [comment]
First of all, thank you for your answer. I still have a question and hope to get your answer. In the paper 2.4 Entity Level Predication section, the relation scores  formula  mentions "For each entity pair $(p^{head}, p^{ptail})$, let $P^{head}$, the set of indices of mentions of the entity $p^{head}$ ... ", how do you determine the indices of these related entities?

**Comment by patverga** [comment]
The model assumes that we already have the entity linking decisions. By that I mean, we know which mentions are referring to the same entities. In the CDR data, this comes directly from the entity annotations and for the CTD data we use an external entity linking model (taken from pubtator).

**Comment by yuanxiaosc** [comment]
Thank you for your patience and this outstanding paper, I can understand the paper.
